@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Sep 13 16:16:46 -0500 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim lab3_TestBench_time_impl -key {Post-Implementation:sim_1:Timing:lab3_TestBench} -tclbatch lab3_TestBench.tcl -view U:/ECE437/Source/Lab3/lab3_TestBench_behav.wcfg -log simulate.log"
call xsim  lab3_TestBench_time_impl -key {Post-Implementation:sim_1:Timing:lab3_TestBench} -tclbatch lab3_TestBench.tcl -view U:/ECE437/Source/Lab3/lab3_TestBench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
